apiVersion: apps/v1
kind: Deployment
metadata:
  name: kipppo-deployment
  labels:
    app: kippo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kippo
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
