---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kippo-deployment
  labels:
    app: kippo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kippo
  template:
    metadata:
      labels:
        app: kippo
    spec:
      containers:
      - name: kippo
        image: rootfox/kippo:1
        ports:
        - containerPort: 2222