---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kippo-deployment
  labels:
    app: kippo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kippo
  template:
    metadata:
      labels:
        app: kippo
    spec:
      containers:
      - name: kippo
        image: rootfox/kippo:latest
        ports:
          - containerPort: 2222
        command: ["/bin/sh"]
        args: ["-c", "cd /kippo && . ./env/bin/activate && twistd -y kippo.tac -n"]
