# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
        auth:
          username: rootfox
          password: $DOCKERHUB_PASSWORD # Environment variable set in CircleCI
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build and push Docker image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $rootfox --password-stdin
            docker build --tag 1 .
            docker tag 1:latest rootfox/kippo:1
            docker push rootfox/kippo:1
